name: "CoreDNS"
version: "1.1.0"
slug: "coredns"
description: "CoreDNS for Home Assistant"
arch:
  - aarch64
  - amd64
  - armv7
  - i386
url: https://github.com/MrRoundRobin/ha-addons/tree/main/coredns
startup: system
ports:
  53/tcp: 53
  53/udp: 53
  80/tcp: 80
  443/tcp: 443
  9153/tcp: 9153
ports_description:
  53/tcp: "DNS server port"
  53/udp: "DNS server port"
  80/tcp: "Health Check"
  443/tcp: "DNS over HTTPS"
  9153/tcp: "Prometheus"
map:
  - ssl
  - addon_config
image: ghcr.io/mrroundrobin/ha-coredns-{arch}
advanced: true
stage: experimental
init: false
